Document: terrexplor-core
Title: Debian terrexplor-core Manual
Author: <insert document author here>
Abstract: This manual describes what terrexplor-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/terrexplor-core/terrexplor-core.sgml.gz

Format: postscript
Files: /usr/share/doc/terrexplor-core/terrexplor-core.ps.gz

Format: text
Files: /usr/share/doc/terrexplor-core/terrexplor-core.text.gz

Format: HTML
Index: /usr/share/doc/terrexplor-core/html/index.html
Files: /usr/share/doc/terrexplor-core/html/*.html
