Document: terrexplor-tile-server
Title: Debian terrexplor-tile-server Manual
Author: <insert document author here>
Abstract: This manual describes what terrexplor-tile-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/terrexplor-tile-server/terrexplor-tile-server.sgml.gz

Format: postscript
Files: /usr/share/doc/terrexplor-tile-server/terrexplor-tile-server.ps.gz

Format: text
Files: /usr/share/doc/terrexplor-tile-server/terrexplor-tile-server.text.gz

Format: HTML
Index: /usr/share/doc/terrexplor-tile-server/html/index.html
Files: /usr/share/doc/terrexplor-tile-server/html/*.html
